name: scroll_shadow_container
description: Neat little shadows on top and bottom of a scrollable container
version: 1.0.1
author: nuc134r <chelman.soft@gmail.com>
homepage: https://github.com/nuc134r/scroll_shadow_container

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: